### ISSUE TITLE
Monthly laser maintenance Jan 2016

### ISSUE THREAD

**Issue by idnorton** [lammspace/documentation#1]
Clean:
- [x] Base
- [x] Honeycomb
- [x] Mirrors

Check:
- [ ] Water level
- [ ] Bubbles in the laser tube

Other maintenance as needed, add comments below.

**Comment by magpiecollective** [comment]
All Done 01/06/2016 except water level & bubbles in laser tube

**Comment by idnorton** [comment]
I knew we had docs somewhere.... :)
